update llvm

diff --git a/llvm/PKGBUILD b/llvm/PKGBUILD
--- a/llvm/PKGBUILD
+++ b/llvm/PKGBUILD
@@ -3,15 +3,13 @@
 
 pkgname=llvm
 pkgdesc="LLVM Toolchain with clang, clang-tools-extra, compiler-rt, openmp, polly, lldb, lld"
-pkgver=15.0.7
-pkgrel=2
+pkgver=16.0.4
+pkgrel=1
 arch=('x86_64')
 url="https://llvm.org/"
 license=('custom:Apache 2.0 with LLVM Exception')
 
-provides=('llvm' "llvm=${pkgver}" 'llvm-libs' 'llvm-ocaml' 'clang' "clang=${pkgver}"
-  'clang-analyzer' 'clang-tools-extra' 'openmp' 'polly' 'compiler-rt' 'lld'
-  'lldb' 'libc++' 'libc++abi' 'libc++experimental')
+provides=('llvm' "llvm=${pkgver}" 'llvm-libs' 'llvm-ocaml' 'clang' "clang=${pkgver}" 'clang-analyzer' 'clang-tools-extra' 'openmp' 'polly' 'compiler-rt' 'lld' 'libc++' 'libc++abi' 'libc++experimental')
 
 # replaces=('llvm' 'llvm-libs' 'llvm-ocaml' 'clang' 'clang-analyzer'
 #   'clang-tools-extra' 'openmp' 'polly' 'compiler-rt' 'lld' 'lldb'
@@ -23,7 +21,7 @@ conflicts=('llvm' 'llvm-libs' 'llvm-ocaml' 'clang' 'clang-analyzer'
   'libc++abi' 'libc++experimental')
 
 depends=('libelf' 'libffi' 'libedit' 'libxml2' 'ncurses')
-_ocaml_ver=4.13.1
+_ocaml_ver=5.0.0
 makedepends=(
   'git' 'ninja' 'cmake' 'clang' 'llvm' 'lld'
   "ocaml>=${_ocaml_ver}" 'ocaml-ctypes' 'ocaml-findlib' 'ocaml-integers' 'ocaml-stdlib-shims'
@@ -31,10 +29,11 @@ makedepends=(
   'python-recommonmark' 'which'
 )
 makedepends_x86_64=('lib32-gcc-libs')
-_commit=8dfdcc7b7bf66834a761bd8de445840ef68e4d1a
+_commit=ae42196bc493ffe877a7e3dff8be32035dea4d07
 source=(
   "llvm-project::git+https://github.com/llvm/llvm-project.git#commit=${_commit:?}"
   'llvm-config.h'
+  'improve-kernel-compile.patch'
 )
 
 sha256sums=('SKIP'
@@ -68,8 +67,7 @@ prepare() {
     exit 1
   )
 
-  # Remove #include <linux/fs.h> to resolve fsconfig_command/mount_attr conflict with glibc 2.36
-  git cherry-pick -n 9cf13067cb5088626ba7ee1ec4c42ec59c7995a0
+  _patch improve-kernel-compile.patch
 
   # Attempt to convert script to Python 3
   2to3 -wn --no-diffs \
@@ -86,91 +84,84 @@ build() {
   # LDFLAGS=${LDFLAGS/-O3/-O2}
 
   cd "${srcdir:?}/llvm-project" || (
-    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Build Failed! \E[0m"
-    exit 1
-  )
+        echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Build Failed! \E[0m"
+        exit 1
+    )
 
-  export CC=clang
-  export CXX=clang++
-  export AR=llvm-ar
-  export AS=llvm-as
-  export NM=llvm-nm
-  export STRIP=llvm-strip
-  export OBJCOPY=llvm-objcopy
-  export OBJDUMP=llvm-objdump
-  export READELF=llvm-readelf
-  export HOSTCC=clang
-  export HOSTCXX=clang++
-  export HOSTAR=llvm-ar
-  export DEBUG_CFLAGS=""
-  export DEBUG_CXXFLAGS=""
-  _extra_build_flags+=(
-    -DCMAKE_C_COMPILER=$(which clang)
-    -DCMAKE_CXX_COMPILER=$(which clang++)
-  )
-  export LD=ld.lld
-  export CC_LD=lld
-  export CXX_LD=lld
-  export HOSTLD=ld.lld
-  _extra_build_flags+=(
-    -DLLVM_USE_LINKER=lld
-    -DCMAKE_LINKER=$(which lld)
-  )
+    if clang --version 2>/dev/null | grep -iq "clang\s*version\s*[0-9]"; then
+        export CC=clang
+        export CXX=clang++
+        export AR=llvm-ar
+        export AS=llvm-as
+        export NM=llvm-nm
+        export STRIP=llvm-strip
+        export OBJCOPY=llvm-objcopy
+        export OBJDUMP=llvm-objdump
+        export READELF=llvm-readelf
+        export HOSTCC=clang
+        export HOSTCXX=clang++
+        export HOSTAR=llvm-ar
+        export DEBUG_CFLAGS="-g0"
+        export DEBUG_CXXFLAGS="-g0"
+        _extra_build_flags+=(
+            -DCMAKE_C_COMPILER=clang
+            -DCMAKE_CXX_COMPILER=clang++
+        )
+    else
+        echo -e "\E[1;31mClang not found. Will use default system compiler! \E[0m"
+    fi
 
-  _build_tests=0
-  _extra_build_flags+=(-DLLVM_BUILD_TESTS=OFF)
-  _build_documentation=0
-  _extra_build_flags+=(-DLLVM_BUILD_DOCS=OFF)
+    if ld.mold --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
+        export LD=ld.lld
+        export CC_LD=lld
+        export CXX_LD=lld
+        export HOSTLD=ld.lld
+        _extra_build_flags+=(-DLLVM_USE_LINKER=lld)
+    fi
 
-  cmake -S llvm -B build -G Ninja \
-    -DCMAKE_BUILD_TYPE=Release \
-    -DCMAKE_INSTALL_PREFIX=/usr \
-    -DLLVM_BINUTILS_INCDIR=/usr/include \
-    -DLLVM_HOST_TRIPLE="${CHOST:?}" \
-    -DLLVM_BUILD_RUNTIME=ON \
-    -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON \
-    -DLLVM_BUILD_LLVM_DYLIB=ON \
-    -DLLVM_LINK_LLVM_DYLIB=ON \
-    -DCLANG_LINK_CLANG_DYLIB=ON \
-    -DLLVM_INSTALL_UTILS=ON \
-    -DLLVM_ENABLE_RTTI=ON \
-    -DLLVM_ENABLE_FFI=ON \
-    -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;lld;lldb;mlir;openmp;polly;pstl" \
-    -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" \
-    -DCLANG_LINK_CLANG_DYLIB=ON \
-    -DLLDB_USE_SYSTEM_SIX=1 \
-    -DLIBOMP_INSTALL_ALIASES=OFF \
-    -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF \
-    -DPOLLY_ENABLE_GPGPU_CODEGEN=ON \
-    -DLLVM_USE_PERF=ON \
-    -DCLANG_DEFAULT_PIE_ON_LINUX=ON \
-    "${_extra_build_flags[@]}"
+    cmake -S llvm -B build -G Ninja \
+        -DCMAKE_BUILD_TYPE=Release \
+        -DCMAKE_INSTALL_PREFIX=/usr \
+        -DLLVM_BINUTILS_INCDIR=/usr/include \
+        -DFFI_INCLUDE_DIR=$(pkg-config --variable=includedir libffi) \
+        -DLLVM_HOST_TRIPLE="${CHOST:?}" \
+        -DLLVM_BUILD_RUNTIME=ON \
+        -DLLVM_BUILD_LLVM_DYLIB=ON \
+        -DLLVM_LINK_LLVM_DYLIB=ON \
+        -DCLANG_LINK_CLANG_DYLIB=ON \
+        -DLLVM_DYLIB_COMPONENTS="all" \
+        -DLLVM_INSTALL_UTILS=ON \
+        -DLLVM_ENABLE_RTTI=ON \
+        -DLLVM_ENABLE_FFI=ON \
+        -DLLVM_ENABLE_BINDINGS=OFF \
+        -DCMAKE_C_FLAGS="$CFLAGS" \
+        -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
+        -DCMAKE_EXE_LINKER_FLAGS="-Wl,-O3,--as-needed -fuse-ld=lld -march=core2" \
+        -DCMAKE_MODULE_LINKER_FLAGS="-Wl,-O3,--as-needed -fuse-ld=lld -march=core2" \
+        -DCMAKE_SHARED_LINKER_FLAGS="-Wl,-O3,--as-needed -fuse-ld=lld -march=core2" \
+        -DLLVM_INCLUDE_BENCHMARKS=OFF \
+        -DLLVM_INCLUDE_TESTS=OFF \
+        -DLLVM_INCLUDE_EXAMPLES=OFF \
+        -DLLVM_BUILD_DOCS=OFF \
+        -DLLVM_INCLUDE_DOCS=OFF \
+        -DLLVM_ENABLE_OCAMLDOC=OFF \
+        -DLLVM_ENABLE_LTO=FULL \
+        -DLLVM_ENABLE_SPHINX=OFF \
+        -DLLVM_ENABLE_DOXYGEN=OFF \
+        -DLLVM_POLLY_LINK_INTO_TOOLS=ON \
+        -DLLVM_TARGETS_TO_BUILD="X86" \
+        -DLLVM_ENABLE_PROJECTS="clang;lld;polly;openmp;compiler-rt" \
+        -DLIBOMP_INSTALL_ALIASES=ON \
+        -DLIBOMP_ENABLE_SHARED=ON \
+        -DOPENMP_ENABLE_LIBOMP_PROFILING=OFF \
+        -DOPENMP_ENABLE_LIBOMPTARGET_PROFILING=OFF \
+        -DLIBOMP_ENABLE_RTTI=OFF \
+        -DLIBOMP_OMPT_SUPPORT=OFF \
+        -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF \
+        -DCLANG_DEFAULT_PIE_ON_LINUX=OFF \
+        "${_extra_build_flags[@]}"
 
-  ninja -C build
-
-  if [[ _build_documentation -eq 1 && _build_bindings -ne 0 ]]; then
-    ninja -C build ocaml_doc
-  fi
-
-}
-
-check() {
-
-  cd "${srcdir:?}/llvm-project" || (
-    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project/build directory! Check Failed! \E[0m"
-    exit 1
-  )
-
-  if [[ _build_tests -eq 1 ]]; then
-    ninja -C build check-llvm
-    ninja -C build check-clang
-    ninja -C build check-clang-tools
-    ninja -C build check-openmp
-    ninja -C build check-polly
-    ninja -C build check-lldb
-    ninja -C build check-lld
-  fi
-
+    ninja -C build
 }
 
 _python_optimize() {
@@ -180,66 +171,64 @@ _python_optimize() {
 }
 
 package() {
-
   cd "${srcdir:?}/llvm-project" || (
-    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Package Failed! \E[0m"
-    exit 1
-  )
+        echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Package Failed! \E[0m"
+        exit 1
+    )
 
-  if [[ _build_documentation -eq 0 ]]; then
-    mkdir -p "${srcdir:?}/llvm-project/build/docs/ocamldoc/html/"
-  fi
+    if [[ _build_documentation -eq 0 ]]; then
+        mkdir -p "${srcdir:?}/llvm-project/build/docs/ocamldoc/html/"
+    fi
 
-  DESTDIR="${pkgdir:?}" ninja -C build install
+    DESTDIR="${pkgdir:?}" ninja -C build install
 
-  pushd llvm/utils/lit || (
-    echo -e "\E[1;31mpushd utils/lit - Package Failed! \E[0m"
-    exit 1
-  )
+    pushd llvm/utils/lit || (
+        echo -e "\E[1;31mpushd utils/lit - Package Failed! \E[0m"
+        exit 1
+    )
 
-  python setup.py install --root="${pkgdir:?}" -O1
-  popd || (
-    echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
-    exit 1
-  )
+    python setup.py install --root="${pkgdir:?}" -O1
+    popd || (
+        echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
+        exit 1
+    )
 
-  if [[ "${CARCH:?}" == "x86_64" ]]; then
-    mv "${pkgdir:?}/usr/include/llvm/Config/llvm-config"{,-64}.h
-    cp "${srcdir:?}/llvm-config.h" "${pkgdir:?}/usr/include/llvm/Config/llvm-config.h"
-  fi
+    if [[ "${CARCH:?}" == "x86_64" ]]; then
+        mv "${pkgdir:?}/usr/include/llvm/Config/llvm-config"{,-64}.h
+        cp "${srcdir:?}/llvm-config.h" "${pkgdir:?}/usr/include/llvm/Config/llvm-config.h"
+    fi
 
-  # Symlink LLVMgold.so from /usr/lib/bfd-plugins
-  # https://bugs.archlinux.org/task/28479
-  mkdir -p "${pkgdir:?}/usr/lib/bfd-plugins"
-  ln -s ../LLVMgold.so "${pkgdir:?}/usr/lib/bfd-plugins/LLVMgold.so"
+    # Symlink LLVMgold.so from /usr/lib/bfd-plugins
+    # https://bugs.archlinux.org/task/28479
+    mkdir -p "${pkgdir:?}/usr/lib/bfd-plugins"
+    ln -s ../LLVMgold.so "${pkgdir:?}/usr/lib/bfd-plugins/LLVMgold.so"
 
-  # Clang
-  site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
-  install -d "${pkgdir:?}/${site_packages}"
-  mv "${pkgdir:?}/usr/lib/"{libear,libscanbuild} "${pkgdir:?}/${site_packages}/"
-  cp -a llvm/bindings/python/llvm "${pkgdir:?}/${site_packages}/"
-  cp -a clang/bindings/python/clang "${pkgdir:?}/${site_packages}/"
+    # Clang
+    site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
+    install -d "${pkgdir:?}/${site_packages}"
+    mv "${pkgdir:?}/usr/lib/"{libear,libscanbuild} "${pkgdir:?}/${site_packages}/"
+    #cp -a llvm/bindings/python/llvm "${pkgdir:?}/${site_packages}/"
+    #cp -a clang/bindings/python/clang "${pkgdir:?}/${site_packages}/"
 
-  mv "${pkgdir:?}"/usr/libexec/* "${pkgdir:?}/usr/lib/clang/"
-  rm -fr "${pkgdir:?}/usr/libexec"
-  sed -i 's|libexec|lib/clang|' \
-    "${pkgdir:?}/usr/bin/scan-build" \
-    "${pkgdir:?}/${site_packages}/libscanbuild/analyze.py"
+    mv "${pkgdir:?}"/usr/libexec/* "${pkgdir:?}/usr/lib/clang/"
+    rm -fr "${pkgdir:?}/usr/libexec"
+    sed -i 's|libexec|lib/clang|' \
+        "${pkgdir:?}/usr/bin/scan-build" \
+        "${pkgdir:?}/${site_packages}/libscanbuild/analyze.py"
 
-  _python_optimize "${pkgdir:?}/usr/share" "${pkgdir:?}/${site_packages}"
+    _python_optimize "${pkgdir:?}/usr/share" "${pkgdir:?}/${site_packages}"
 
-  # Remove html documentation
-  if [[ _build_documentation -eq 0 ]]; then
-    rm -fr "${pkgdir:?}/usr/share/doc"
-  fi
+    # Remove html documentation
+    if [[ _build_documentation -eq 0 ]]; then
+        rm -fr "${pkgdir:?}/usr/share/doc"
+    fi
 
-  # Licenses
-  install -Dm644 "${srcdir:?}/llvm-project/llvm/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/llvm-LICENSE"
-  install -Dm644 "${srcdir:?}/llvm-project/clang/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-LICENSE"
-  install -Dm644 "${srcdir:?}/llvm-project/clang-tools-extra/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-tools-extra-LICENSE"
-  install -Dm644 "${srcdir:?}/llvm-project/compiler-rt/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/compiler-rt-LICENSE"
-  install -Dm644 "${srcdir:?}/llvm-project/lld/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/lld-LICENSE"
-  install -Dm644 "${srcdir:?}/llvm-project/lldb/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/lldb-LICENSE"
-  install -Dm644 "${srcdir:?}/llvm-project/polly/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/polly-LICENSE"
-  install -Dm644 "${srcdir:?}/llvm-project/openmp/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/openmp-LICENSE"
+    # Licenses
+    install -Dm644 "${srcdir:?}/llvm-project/llvm/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/llvm-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/clang/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/clang-tools-extra/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/clang-tools-extra-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/compiler-rt/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/compiler-rt-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/lld/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/lld-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/polly/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/polly-LICENSE"
+    install -Dm644 "${srcdir:?}/llvm-project/openmp/LICENSE.TXT" "${pkgdir:?}/usr/share/licenses/${pkgname}/openmp-LICENSE"
 }
